version: "3.3"

services:
  app:
    container_name: jmdkh-mltb-s
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "801:80"
